export const demoCredentials = {
  email: "anurag@gmail.com",
  password: "anurag",
};

export const reducerAction = {
  API_DATA: "API_DATA",
  SORT_LOW_TO_HIGH: "LOW_TO_HIGH",
  SORT_HIGH_TO_LOW: "HIGH_TO_LOW",
  CATEGORY_STOCKS: "CATEGORY_STOCKS",
  CATEGORY_FOREX: "CATEGORY_FOREX",
  CATEGORY_CRYPTO: "CATEGORY_CRYPTO",
  CATEGORY_CHARTING: "CATEGORY_CHARTING",
  CATEGORY_INVESTMENT: "CATEGORY_INVESTMENT",
  SELECT_RANGE: "RANGE",
  SELECT_RATING: "RATING",
  CLEAR_FILTER: "CLEAR_FILTER",
  UPDATE_CART: "UPDATE_CART",
  UPDATE_WISHLIST: "UPDATE_WISHLIST",
  CLEAR_CART_WISHLIST: "CLEAR_CART_WISHLIST",
  LOGIN_USER_DATA: "LOGIN_API_DATA",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  CHANGE_DEFAULT_ADDRESS: "CHANGE_DEFAULT_ADDRESS",
};
